import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";

import { Hero } from "../components/Hero";
import { InnerApp } from "../components/InnerApp/InnerApp";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Kontist Umsatzsteuer Voranmeldung</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <div suppressHydrationWarning={true}>
          {process.browser && <InnerApp />}
        </div>
      </main>
    </div>
  );
};

export default Home;
